import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  whitebg: {
    backgroundColor: '#EDEDED',
  },
  keyboardView: {
    backgroundColor: '#EDEDED',
    flex: 1,
  },
  input: {
    borderColor: '#2A00A5',
    padding: 10,
  },
  form: {
    placeholderTextColor: "#2A00A5",
    // placeholderTextColor: '#76757D',
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#FFFFFF',
    onselect: 'none',
    boxShadow: 'none',
    backgroundColor: '#fff',
  },
  buttonGroup: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  button: {
    textAlign: 'center',
    backgroundColor: '#FFF',
    borderColor: '#2A00A5',
    borderWidth: 2,
    padding: 10,
    borderRadius: 30,
    width: '100%',
    flex: 1,
  },
  buttonText: {
    color: '#2A00A5',
    fontWeight: '700',
  },
  buttonPurple: {
    textAlign: 'center',
    backgroundColor: '#2A00A5',
    padding: 10,
    borderRadius: 30,
    width: '100%',
    flex: 1,
  },
  buttonTextWhite: {
    color: '#FFF',
    fontWeight: '700',
  },
  modal: {
    width: '100%',
    borderBottomWidth: 0,
    textAlign: 'center',
  },
  modalView: {
    backgroundColor: '#EDEDED',
    width: '100%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    textAlign: 'center',
    position: 'fixed',
    bottom: 0,
  },    
  modalHeader: {
    paddingTop: 20,
    paddingBottom: 10, 
    paddingHorizontal: 15,
    marginLeft: 10,
    display: 'flex',
    alignItems: 'center',
    width: '97.5%',
    alignContent: 'center',
    textAlign: 'center',
    flexDirection:'row',

  },
  modalHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  modalHeaderText: {
    fontWeight: '600',
    textAlign: 'center',
    justifyContent: 'center',
  },
  bottomModal: {
    marginTop: 'auto',
    borderBottomWidth: 0,
  },
  modalFooter: {
    borderTopWidth: 0, 
    elevation: 0, 
    margin: 0,
  },
  lineSeparator: {
    borderBottomColor: "#CECED0",
    borderBottomWidth: 1,
    display: "flex",
    width: "95%",
    alignSelf: "flex-end",
  },
  circleRow: {
    borderRadius: 7.5,
    backgroundColor: "white",
    marginVertical: 16,
    marginHorizontal: 16,
  },
  priorityText: {
    paddingLeft: 14,
    fontSize: 16,
  },
  makesRow: {
    display: "flex", 
    flexDirection: "row", 
    alignItems: "center",
    marginHorizontal: 16,
    marginVertical: 16,
  },
  makesRowPressable: {
    display: "flex", 
    flexDirection:"row", 
    width: "90%", 
  },
  icon: {
    position: 'absolute',
    top: 4,
    right: 4,
  },
});
